submission_data_path = "FinalPro"
url = "http://ec2-18-191-24-254.us-east-2.compute.amazonaws.com/results/"
download_data_path = "downloads"
split_data_path = "train_val"
train_path = "all_data/training"
val_path = "all_data/validation/query"
best_model_path = "best_model.pth"
best_state_path  = "best_state.pth"